---
- name: Pull docker image of scientific-calculator
  hosts: all
  tasks:
    - name: Pull scientific-calculator image
      shell: docker pull gaurangi99/spe-mini-project

    - name: run container
      shell: docker run -i -t --name calculator -d gaurangi99/spe-mini-project